### ISSUE TITLE
Doesn’t work in Firefox?

### ISSUE THREAD

**Issue by ahrjarrett** [ahrjarrett/react-speak#3]
@lefrenk reported that using `react-speak` in Firefox results in the following error:

`TypeError: window.SpeechRecognition is not a constructor`

TODO read the [Firefox Speech Recognition API Docs](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition) to determine how the Chrome and Firefox APIs differ

**Comment by frankfaustino** [comment]
#4 — fix for FireFox 'SpeechRecognition is not a constructor'

**Comment by ahrjarrett** [comment]
Fixed in [PR #4](https://github.com/ahrjarrett/react-speak/commit/4e80e06438917f1cae1a48206bb103e73af760a3). Thank you @lefrenk!
